### ISSUE TITLE
Separate domains with network-specific URL routing

### ISSUE THREAD

**Issue by natachadelarosa** [subspace/blockexplorer#165]
Make different domains accessible through network-specific routing.

Example:
For gemini-2c: `https://subspace.github.io/blockexplorer/gemini-2c/blocks`
For gemini-3d:  `https://subspace.github.io/blockexplorer/gemini-3d/blocks`

```[tasklist]
### Tasks
- [ ] https://github.com/subspace/blockexplorer/issues/173
- [ ] https://github.com/subspace/blockexplorer/issues/174
- [ ] https://github.com/subspace/blockexplorer/issues/175
- [ ] https://github.com/subspace/blockexplorer/issues/177
```

```[tasklist]
### Acceptance criteria
- [x] The URL specifies the network
- [ ] Legacy links fallback to `gemini-2c`
- [x] Search placeholder prompt the network
- [ ] Make the networks name properly identify the version, sample: `Gemini 3c`
- [x] UI remembers which network was previously selected
- [x] UI remembers the selected network if the tab or window was closed
```

**Comment by natachadelarosa** [comment]
@isSerge Do you think this is complete? 
Is there anything missing, in your opinion?

**Comment by stefanopepe** [comment]
UI note: we believe that using `Gemini IIIc` in the dropdown network selection menu is a bit confusing, so we are opting by now with the "technical" definition `Gemini 3c` instead:

![Screen Shot 2023-03-01 at 15 30 46](https://user-images.githubusercontent.com/6222429/222258411-2a5c9f06-d9c2-4227-945e-def04267a7c8.png)

Pros:
- it is the same as Polkadot JS explorer (see here) and our name convention on GitHub
Cons:
- it is not following the community and blog standards, which are using "Roman" numerals, e.g. `Gemini III`

**Comment by isSerge** [comment]
> @isSerge Do you think this is complete? Is there anything missing, in your opinion?

- Currently, we use hash router, so URLs would be like `https://subspace.github.io/blockexplorer/#/gemini-2c/blocks`
- Also not sure we need to specify chain letters (c, b, d...), since the next iteration will probably replace the previous one. I think 'Gemini-2' and 'Gemini-3' should be enough. @stefanopepe please, let us know what you think.

**Comment by isSerge** [comment]
> > Also not sure we need to specify chain letters (c, b, d...), since the next iteration will probably replace the previous one. I think 'Gemini-2' and 'Gemini-3' should be enough. @stefanopepe please, let us know what you think.
> 
> It is not a great assumption that we will replace the previous Gemini 3 when we release a new one, so I would keep the letter.

does it mean we have to maintain all those droplets and set up new ones for each release?

**Comment by jfrank-summit** [comment]
I think it is better to plan for the possibility so leaving the letter iterator on makes the most sense to me. It is likely that we will launch 3d while still maintaining 3c.

**Comment by stefanopepe** [comment]
@natachadelarosa added another "task" which: default to `Gemini-3c` on page load, to support the upcoming community launch (`Gemini-2c` explorer use cases will be "legacy" from the previous incentivized testnet phases)

**Comment by isSerge** [comment]
Probably UI app also has to remember what network the user has selected. Currently, if I select Gemini-3 and go to an Extrinsic or Event page and refresh - it will show 404 because there is no such event or extrinsic on Gemini-2, which is the default network.

**Comment by stefanopepe** [comment]
Added two more acceptance criteria, to test the "remember network" functionality UX

**Comment by stefanopepe** [comment]
Run a few tests:
- Legacy links fail to route to Gemini II, see [here](https://subspace.github.io/blockexplorer/#/accounts/0x14682f9dea76a4dd47172a118eb29b9cf9976df7ade12f95709a7cd2e3d81d6c)
- The dropdown menu doesn't display the network name, as defined [here](https://github.com/subspace/blockexplorer/issues/165#issuecomment-1450807655) and confirmed by Jeremy [here](https://github.com/subspace/blockexplorer/issues/165#issuecomment-1451953862)

**Comment by stefanopepe** [comment]
Run tests, it all works.
good to go for me

**Comment by natachadelarosa** [comment]
Thank you, @stefanopepe!
