### ISSUE TITLE
Support all valid SS58 addresses

### ISSUE THREAD

**Issue by natachadelarosa** [subspace/blockexplorer#188]
Currently, the backend supports addresses written in the `stAckE2Fdgu....` form. It should also support the `5FKvfXnd.......` structure as well.

```[tasklist]
### Acceptance criteria
- [x] Users can search by both style addresses
```

```[tasklist]
### Tasks
- [ ] https://github.com/subspace/blockexplorer/issues/196
- [ ] https://github.com/subspace/blockexplorer/issues/197
```

**Comment by nazar-pc** [comment]
TO be specific, any valid Substrate SS58 address should be supported, not just those two
