### ISSUE TITLE
[epic]Allow search by hashes for Extrinsics and Blocks

### ISSUE THREAD

**Issue by natachadelarosa** [subspace/blockexplorer#224]
The current search bar allows search by hash only for accounts. Blocks and extrinsics are needed to use block id or extrinsic id, respectively.

This task adds the functionality needed to search blocks and extrinsics to be searchable by their hashes.

```[tasklist]
### Acceptance criteria
- [x] It can find extrinsics, blocks by their hash
- [x] In case of colliding extrinsic hash, show both and make them distinguishable
- [ ] It works across Gemini 3d domains
```

```[tasklist]
### Tasks
- [ ] https://github.com/subspace/blockexplorer/issues/241
- [ ] https://github.com/subspace/blockexplorer/issues/232
```
