### ISSUE TITLE
[Epic] - Update Account page UI

### ISSUE THREAD

**Issue by isSerge** [subspace/blockexplorer#234]
Updated Account page according to new designs on [Figma](https://www.figma.com/file/nRWatk3fZ3Rg2SYjbRLaIu/Subspace---Block-Explorer?node-id=1026-4&t=q3JQqbx8grOwPRKE-0)

Skip filtering for extrinsics - there will be a separate issue for filters. 

When a user clicks `See All Rewards` it should navigate to a separate page `https://explorer.subspace.network/#/<chain>/accounts/<address>/rewards`

Address issues mentioned in #172 

```[tasklist]
### Tasks
- [ ] https://github.com/subspace/blockexplorer/issues/244
- [ ] https://github.com/subspace/blockexplorer/issues/245
- [ ] https://github.com/subspace/blockexplorer/issues/246
- [ ] https://github.com/subspace/blockexplorer/issues/247
```
