### ISSUE TITLE
Add Graphql API docs

### ISSUE THREAD

**Issue by isSerge** [subspace/blockexplorer#239]
To improve the developer experience and provide detailed information on using the GraphQL API, we need to add the API documentation to the repository. The documentation should include details about the types in the schema.

#### Task List

- [x] Create a new file named `api.md` in the `squid-blockexplorer` directory of the repository
- [x] Add the GraphQL API documentation to the `api.md` file
- [x] Update the `README.md` file to include a section that refers to the GraphQL API documentation
